### PR TITLE
Allow HTTPX 0.23

### PR DESCRIPTION
**Pull request by nshaaban-cPacket**
Fixes: https://github.com/sanic-org/sanic-testing/issues/38

### CODE REVIEW

**Comment by nshaaban-cPacket** [comment]
@ahopkins do you have a second to review so this repo's no longer vulnerable to https://github.com/advisories/GHSA-h8pj-cxx2-jfg2 ?

**Comment by amn41** [comment]
just commenting to mention that sanic is a dependency of [rasa](github.com/rasaHQ/rasa) and it would be a big help for us if this vulnerability were resolved.

**Comment by ahopkins** [comment]
Will be resolved in the coming day or two with the upcoming release.

**Review by ahopkins — APPROVED** [review]

**Comment by ancalita** [comment]
@ahopkins would this dependency be updated in `sanic` versions `20.12` LTS  & `21.12` LTS as well? Do you have a timeline please?

**Comment by ahopkins** [comment]
LTS versions will be released tonight or tomorrow with v22.6.

**Comment by ahopkins** [comment]
@ancalita Trying to make the change to v20.12 is going to be a PITA because there have been a number of breaking changes in the `httpx` API since then. This was one of the motivating factors for moving `sanic.testing` to `sanic-testing`.

**Comment by ahopkins** [comment]
v0.8.3 is released now and can be used with 21.12LTS. Starting after v22.3 the versioning should track easier.

**Pull request merged**
